# Generated by Django 4.0.2 on 2022-07-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='movieid',
            field=models.CharField(max_length=20),
        ),
    ]
