# Generated by Django 4.0.6 on 2022-07-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='movieid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movies')),
            ],
        ),
    ]
