# Generated by Django 4.0.6 on 2022-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_movies_movieid_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
